# Importing libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Loading dataset

In [2]:
df=pd.read_csv('Advertising.csv')

In [3]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.tail()

Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [5]:
df.shape

(200, 5)

In [6]:
df.size

1000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  200 non-null    int64  
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB


In [8]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [9]:
df.isna().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, TV, Radio, Newspaper, Sales]
Index: []

In [11]:
df.duplicated().sum()

0

In [12]:
df.columns

Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [13]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [14]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

# Linear Regression

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_percentage_error

In [19]:
y=df['Sales']
x=df.drop(['Sales'],axis=1)

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [21]:
lr=LinearRegression()

In [22]:
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
lr.coef_

array([0.04405928, 0.1992875 , 0.00688245])

In [24]:
lr.intercept_

2.7089490925159048

In [25]:
y_pred=lr.predict(x_test)

In [26]:
y_pred[:5]

array([16.5653963 , 21.18822792, 21.55107058, 10.88923816, 22.20231988])

In [27]:
r2_score(y_test,y_pred)

0.8609466508230369

In [30]:
mean_squared_error(y_test,y_pred)

3.796797236715217

In [29]:
mean_absolute_percentage_error(y_test,y_pred)

0.16298720118158336

In [31]:
df_test_pred=pd.DataFrame({'Actual Values':y_test,"Predicted values":y_pred})

In [32]:
df_test_pred

Actual Values  Predicted values
95            16.9         16.565396
15            22.4         21.188228
30            21.4         21.551071
158            7.3         10.889238
128           24.7         22.202320
115           12.6         13.355569
69            22.3         21.196925
170            8.4          7.350285
174           11.5         13.275471
45            14.9         15.124495
66             9.5          9.014430
182            8.7          6.525428
165           11.9         14.302060
78             5.3          8.970260
186           10.3          9.456796
177           11.7         12.004544
56             5.5          8.915494
152           16.6         16.156193
82            11.3         10.295829
68            18.9         18.724736
124           19.7         19.768218
16            12.5         13.774690
148           10.9         12.496389
93            22.2         21.535018
65             9.3          7.608607
60             8.1          5.611980
84            21.7         20.917595
67            13.4         11.806277
125           10.6          9.080766
132            5.7          8.514120
9             10.6         12.176049
18            11.3          9.969194
55            23.7         21.730090
75             8.7         12.777706
150           16.1         18.101136
104           20.7         20.075908
135           11.6         14.262026
137           20.8         20.938265
164           11.9         10.839388
76             6.9          4.381906
79            11.0          9.513324
197           12.8         12.404863
38            10.1         10.170454
24             9.7          8.090814
122           11.6         13.163884
195            7.6          5.224355
29            10.5          9.288938
19            14.6         14.093307
143           10.4          8.690245
86            12.0         11.661198
114           14.6         15.718484
173           11.7         11.631569
5              7.2         13.353607
126            6.6         11.153147
117            9.4          6.336368
73            11.0          9.761580
140           10.9          9.419571
98            25.4         24.255165
172            7.6          7.695191
96            11.7         12.153176

# Predictive analysis

In [33]:
array=np.array([100,50,50])
array

array([100,  50,  50])

In [34]:
new_array=array.reshape(1,-1)
new_array

array([[100,  50,  50]])

In [35]:
y_pred_array=lr.predict(new_array)
y_pred_array

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([17.42337464])